services:
  db:
    image: postgres:15-alpine
    container_name: postgres_alquileres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_alquileres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
